[package]
name = "project3"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
dioxus-router = "0.4.0"
argon2 = "0.5.3"
# sqlite = "0.36.1"
rusqlite = "0.30.0"
sha2 = "0.10.8"
